---
apiVersion: v1
kind: Service
metadata:
  name: simple-webhook
  namespace: default
  labels:
    name: simple-webhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 3000
  selector:
    name: simple-webhook 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webhook
  namespace: default
  labels:
    name: simple-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple-webhook  
  template:
    metadata:
      name: simple-webhook 
      labels:
        name: simple-webhook
    spec:
      containers:
        - name: webhook
          image: vijaydcrust/simplewebhook
          imagePullPolicy: Always
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 00Mi
              cpu: 300m
          securityContext:
            readOnlyRootFilesystem: true
